### ISSUE TITLE
[egg-astro-colony.json] Install script contains unnecessary and outdated config generation

### ISSUE THREAD

**Issue by danny6167** [Ptero-Eggs/game-eggs#10]
The install script generates a configuration file.
This is not needed as the ini parser in Pterodactyl will correctly generate this file.
It's also out of date, referencing keys that don't exist

**Comment by Red-Banana-Official** [comment]
I looked into this, and it seems that it indeed doesn't need the script to generate the ServerSettings.ini file, it actually causes a duplicate in the config.

Without the script generating the ServerSettings.ini, it shows the correctly put together script, using the users-set variables.

The script creates a second line, with the same values, under:
[Script/AstroColony.EHServerSubsystem] > when the server expects > [/Script/ACFeature.EHServerSubsystem]


I will make a PR to reflect this change shortly.

**Comment by danny6167** [comment]
Thanks for that. It was duplicated because I updated the config parser when the devs changed the key path, but I hadn't realized at the time that the install script also contained this unneeded.

I haven't touched the wine one at all, so it likely needs both the config parser settings updated, and the part in the install script removed.

**Comment by danny6167** [comment]
Resolved by https://github.com/Ptero-Eggs/game-eggs/pull/16
