### ISSUE TITLE
[egg-project-zomboid.json] MaxPlayers not working

### ISSUE THREAD

**Issue by FonsecaBF** [Ptero-Eggs/game-eggs#6]
### Panel Version

1.11.10

### Wings Version

1.11.13

### Service

projectzomboid

### Modified

No, I did not modify the egg

### Expected Behavior

Maxplayers does not work you put the number of players to the server but it does not change when started the server.

### Actual Behavior

Maxplayers does not work you put the number of players to the server but it does not change when started the server.

### Steps To Reproduce

Create a server.
Enter the number of slots you want
Start the server and it does not work

### Install logs

not

**Comment by danny6167** [comment]
I've looked into this, and there is no way to pass a MaxPlayers value over the command line.

Normally we would use the panels ini parser to set the value in the servers config file but this egg is setup to allow people to change the "server name", that changes the name of the config file that is read. The panel has no way of editing a config file with a dynamic name.

Likely the best we can do right now is remove the invalid configuration option from the egg.
