### ISSUE TITLE
[egg-pavlov-v-r.json] Server start failed libc++.so: file too short

### ISSUE THREAD

**Issue by KatieGames** [Ptero-Eggs/game-eggs#8]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

Pavlov VR

### Modified

No, I did not modify the egg

### Expected Behavior

Install server
Start it
Server runs

### Actual Behavior

Install server
Start it
Server fails to start erroring as follows
![image](https://github.com/user-attachments/assets/05818257-47ce-45b1-b54f-d9edb31805ea)

Main error is:
./Pavlov/Binaries/Linux/PavlovServer-Linux-Shipping: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libc++.so: file too short

### Steps To Reproduce

Install the server
Run the server

### Install logs

https://ptero.co/qizajunoka

**Comment by danny6167** [comment]
Hi @KatieGames,

You seem to be using an old docker image to run that server.
Make sure your [egg is up-to-date](https://pterodactyleggs.com/egg/6735ff644924a4e9bbcc0818) and that you haven't got the docker image overridden. For that egg it should be `ghcr.io/ptero-eggs/steamcmd:ubuntu`

Fix that up and try again for me please.

**Comment by KatieGames** [comment]
I just repulled the egg and reimported it to ptero and that seemed to work. I think I was having my issue because I had updated a previous egg to this one and it had missed something, instead of importing it as a new one. I imported the egg as a new one into the nest and it seems to be working fine. Thank you!
